### ISSUE TITLE
那个版本的tv可以用啊

### ISSUE THREAD

**Issue by hsiun** [lyz8jj0/mac-teamviewer-crack#2]

**Comment by lyz8jj0** [comment]
13的可以使用

**Comment by lyz8jj0** [comment]
链接: https://pan.baidu.com/s/1S1CzoqJQSGEnPKuBi9GyPg 密码:82by	(我使用的版本)
链接:https://pan.baidu.com/s/1h8zU4jw-RibmP-JsjRGcNg 密码:vgfl	(小伙伴提供的版本)

**Comment by gongchy** [comment]
发现如果是14版本的，可以通过卸载14的，装上13的，然后使用这个脚本解决问题

**Comment by gongchy** [comment]
> 发现如果是14版本的，可以通过卸载14的，装上13的，然后使用这个脚本解决问题

算是曲线救国吧

**Comment by hsiun** [comment]
好的，谢谢啊
